### ISSUE TITLE
modified_hinge_loss.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

### ISSUE THREAD

**Issue by neverneverendup** [abhipec/fnet#4]
Hello author，
I try to run your updated tensorflow 1.10 fetc code.But I meet the same error occurred in your 0.10. tensorflow code.
Error message: 
Traceback (most recent call last):
  File "../main_fnet_train.py", line 36, in <module>
    import models.FnetClassificationModel as model
  File "/home/guozhiyuan/bijiao/FgEC-master/src/models/FnetClassificationModel.py", line 9, in <module>
    import models.modified_hinge_loss
  File "/home/guozhiyuan/bijiao/FgEC-master/src/models/modified_hinge_loss.py", line 14, in <module>
    loss_module = tf.load_op_library(library_directory + '/modified_hinge_loss.so')
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/guozhiyuan/bijiao/FgEC-master/src/models/../lib/modified_hinge_loss.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

Please tell me how to fix this problem.Thanks~

**Comment by abhipec** [comment]
Can you please specify your installed TensorFlow version along with the gcc version?

**Comment by abhipec** [comment]
@neverneverendup I have updated the compilation file available at : https://github.com/abhipec/FgEC/blob/master/src/lib/compile_gcc_5.bash
This is working well on TensorFlow 1.12 along with g++ 7.3.0 version.
